### ISSUE TITLE
presentation Qs

### ISSUE THREAD

**Issue by dansinker** [sinker/trumppoopwatch.org#3]
so right now this is a single page. I think that's right. It's still really janky. I want to actually keep the janky aesthetic for the most part. a few things:

1) if, as floated in #1 we decide to go with a full database, we'll need to build out a page to display the definitive list.

~~2) I really want the main poop emoji to slowly spin~~

3) what are the accessibility questions that need to be addressed when you use emoji in text

~~4) I haven't checked shit on mobile~~

**Comment by dansinker** [comment]
got the poop spinning with https://github.com/sinker/trumppoopwatch.org/commit/77568122f8a40a91c42fc94e561649cc9e4bb78a

**Comment by dansinker** [comment]
have checked on mobile and it's a shitshow (literally) so am going to create a new issue for that.

**Comment by dansinker** [comment]
mobile is now fixed.

**Comment by tsaylor** [comment]
Using VoiceOver screen reading on a mac, the text description of the emoji is read aloud. 

Trump 💩Watch - "Trump smiling pile of poo watch"
It has been 1 week and 3 days since Trump's last 💩 - "It has been one week and three days since Trump's last smiling pile of poo".

So basically you've opened a portal to the good timeline. 😁

Checked in with my accessibility expert at work, she couldn't think of anything to worry about besides screen reading.

**Comment by dansinker** [comment]
omg that is amazing.

**Comment by dansinker** [comment]
with that, I'm going to close this issue and move historical database & presentation into a separate issue.
